import { Advertisement } from "./models/advertisement";

const testAdvertisements: Advertisement[] = [
    {
        id: 1,
        title: "Casa en el Centro",
        description: "Una hermosa casa ubicada en el centro de la ciudad.",
        price: 150000,
        status: "available",
        publicationDate: new Date("2023-09-01"),
        property: {
            type: "house",
            location: "Ciudad Centro",
            area: 120,
            bathrooms: 2,
            bedrooms: 3,
        },
        images: [],
        owner: {
            name: "Juan",
            email: "juan@example.com",
            password: "123456",
            phone: "555-0101",
            profile: "owner",
            isVerified: true,
        },
    },
    {
        id: 2,
        title: "Apartamento Moderno",
        description: "Elegante apartamento con todas las comodidades modernas.",
        price: 95000,
        status: "available",
        publicationDate: new Date("2023-08-15"),
        property: {
            type: "apartment",
            location: "Barrio Moderno",
            area: 80,
            bathrooms: 1,
            bedrooms: 2,
        },
        images: [],
        owner: {
            name: "Ana",
            email: "ana@example.com",
            password: "password",
            phone: "555-0202",
            profile: "owner",
            isVerified: true,
        },
    },
    {
        id: 3,
        title: "Estudio Céntrico",
        description: "Estudio ideal para estudiantes en una ubicación estratégica.",
        price: 50000,
        status: "available",
        publicationDate: new Date("2023-07-20"),
        property: {
            type: "studio-apartment",
            location: "Centro",
            area: 40,
            bathrooms: 1,
            bedrooms: 1,
        },
        images: [],
        owner: {
            name: "Carlos",
            email: "carlos@example.com",
            password: "abc123",
            phone: "555-0303",
            profile: "renter",
            isVerified: true,
        },
    },
    {
        id: 4,
        title: "Cabaña en la Montaña",
        description: "Escapada perfecta en una cabaña con vistas increíbles a la montaña.",
        price: 80000,
        status: "taken",
        publicationDate: new Date("2023-06-10"),
        property: {
            type: "cabin",
            location: "Sierra Nevada",
            area: 60,
            bathrooms: 1,
            bedrooms: 2,
        },
        images: [],
        owner: {
            name: "Luisa",
            email: "luisa@example.com",
            password: "secret",
            phone: "555-0404",
            profile: "owner",
            isVerified: true,
        },
    },
    {
        id: 5,
        title: "Lote con Potencial",
        description: "Lote ubicado en zona en desarrollo, ideal para inversión.",
        price: 30000,
        status: "available",
        publicationDate: new Date("2023-05-05"),
        property: {
            type: "lot",
            location: "Periferia",
            area: 300,
            bathrooms: 0,
            bedrooms: 0,
        },
        images: [],
        owner: {
            name: "Miguel",
            email: "miguel@example.com",
            password: "pass1234",
            phone: "555-0505",
            profile: "owner",
            isVerified: false,
        },
    },
    {
        id: 6,
        title: "Granja en Venta",
        description: "Extensa granja con posibilidades de expansión en un ambiente rural.",
        price: 200000,
        status: "available",
        publicationDate: new Date("2023-04-15"),
        property: {
            type: "farm",
            location: "Campo Verde",
            area: 500,
            bathrooms: 3,
            bedrooms: 4,
        },
        images: [],
        owner: {
            name: "Elena",
            email: "elena@example.com",
            password: "elena2023",
            phone: "555-0606",
            profile: "owner",
            isVerified: true,
        },
    },
    {
        id: 7,
        title: "Habitación Acogedora",
        description: "Habitación disponible en casa compartida, perfecta para estudiantes.",
        price: 20000,
        status: "pending",
        publicationDate: new Date("2023-03-25"),
        property: {
            type: "room",
            location: "Suburbio",
            area: 20,
            bathrooms: 1,
            bedrooms: 1,
        },
        images: [],
        owner: {
            name: "Sofía",
            email: "sofia@example.com",
            password: "sofia321",
            phone: "555-0707",
            profile: "renter",
            isVerified: false,
        },
    },
    {
        id: 8,
        title: "Espacio Sin Definir",
        description: "Propiedad en proceso de planificación, tipo indefinido.",
        price: 0,
        status: null,
        publicationDate: new Date("2023-02-10"),
        property: {
            type: "",
            location: "Por definir",
            area: 0,
            bathrooms: 0,
            bedrooms: 0,
        },
        images: [],
        owner: {
            name: "Mariana",
            email: "mariana@example.com",
            password: "mariana!",
            phone: "555-0808",
            profile: "owner",
            isVerified: true,
        },
    },
];

export default testAdvertisements;